### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by grinapo**
Add usage (please verify whether I interpreted the flags correctly, and whether they're still relevant) and block to block example.

### CODE REVIEW

**Comment by dop251** [comment]
Hi. Thanks for submitting, however I don't think it's a good idea to have this in more than one place. This would mean every time something changes with the flags, I'll need to remember to update the README as well (which I won't). It is also kind of redundant, because all you need to do to get this is run the command without arguments.

**Comment by grinapo** [comment]
Fine by me, but then please update the runtime help accordingly, since it's missing a lot of detailed explanations.
Thank you!

**Comment by dop251** [comment]
What's missing exactly? Please bear in mind that some of the flags (source, target, calc-progress, sync-progress) are only used when diskrsync is started remotely, by another diskrsync, for that reason they have been deliberately made hidden.

**Comment by grinapo** [comment]
What I wrote was two parts:
1) specific example and _a bit more detailed_ description.
- ssh-flags: additional args for ssh (example: `--ssh-flags="-i ~/.ssh/backup.key"`)
    - This has been mentioned 
- no-compress: do not compress the target image. **This flag is required if the target is a block device.**
    - This is absolutely necessary (unless I'm mistaken) when copying blockdev-to-blockdev, worths mentioning.
- calc-progress: display prograss bar for hash calulation phase
- sync-progress: display progress bar for synchronisation phase
    - I am not sure why these would be useful apart from `verbose` but they seem to be present, so mentioning it.
- verbose: display both progress bars and additional info on block size and transferred data
    - More detailed description of what it does exactly.
- source: (default) diskrsync is the source and it connects to the remote target
- target: diskrsync connects the remote source
    - These may be internal flags, then it would be useful to mention that in their description.
- src/dst: `[[user@]host:]path` local or remote file/device
    - This was mentioned.

2. I also have added some examples, namely one showing dlockdev-to-blockdev copy:

```shell
diskrsync --verbose --no-compress /dev/mapper/vg0-snap_vm-101-disk-0 user@remotehost:/dev/rbd7
```

This command transfers local source block device (lvm snapshot) to remote block device (rados block device in the example).

----
As for deliberately hiding, it's find, but the help show them, so they are not that hidden, but the help _description_ does not tell what they are, why they are hidden and why or why not they shall be used.

I usually try to help enhancing documentation, that was my purpose here and now as well. If you do not need that please tell me, and I will stop doing that.

**Pull request closed without merging**
